ALTER TABLE announcements
    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;

ALTER TABLE users
    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;

ALTER TABLE crop_categories
    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;

ALTER TABLE crops
    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;

ALTER TABLE orders
    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;

ALTER TABLE order_items
    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;

ALTER TABLE cooperative_members
    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;

ALTER TABLE cooperative_pools
    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;

ALTER TABLE crops_inventory
    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;